agent_name: "fewshot"
# LLM hyperparameters
llm:
  series: "gemini_dev"
  model_name: "gemini-3-flash-preview"
  temperature: 0.0
  max_tokens: 128
  bench_overrides:
    spider:
      max_tokens: 512
    cosql:
      max_tokens: 512
    bird:
      max_tokens: 1024
    ds_1000:
      max_tokens: 1024
    hotpotqa_distract:
      max_tokens: 512
