agent_name: "ma_rr"
seed: 42
warmup_steps: 0
llms:
  - name: "gemini3_a"
    series: "gemini_dev"
    model_name: "gemini-3-flash-preview"
    temperature: 0.0
    max_tokens: 128
    bench_overrides:
      spider:
        max_tokens: 512
      cosql:
        max_tokens: 512
      bird:
        max_tokens: 1024
      ds_1000:
        max_tokens: 1024
      hotpotqa_distract:
        max_tokens: 512
  - name: "gemini3_b"
    series: "gemini_dev"
    model_name: "gemini-3-flash-preview"
    temperature: 0.0
    max_tokens: 128
    bench_overrides:
      spider:
        max_tokens: 512
      cosql:
        max_tokens: 512
      bird:
        max_tokens: 1024
      ds_1000:
        max_tokens: 1024
      hotpotqa_distract:
        max_tokens: 512
  - name: "gemini3_c"
    series: "gemini_dev"
    model_name: "gemini-3-flash-preview"
    temperature: 0.0
    max_tokens: 128
    bench_overrides:
      spider:
        max_tokens: 512
      cosql:
        max_tokens: 512
      bird:
        max_tokens: 1024
      ds_1000:
        max_tokens: 1024
      hotpotqa_distract:
        max_tokens: 512
rag:
  embedding_model: "BAAI/bge-base-en-v1.5"
  top_k: 16
  order: "similar_at_bottom"
  rag_filename: null
  seed: 42
